# !/bin/bash
r="\e[1;31m"
g="\e[4;32m"
y="\e[4;33m"
b="\e[1;34m"
m="\e[2;35m"
c="\e[1;36;47m"
w="\e[1;37;43m"
no="\e[0m"
printf "${r} ERROR ${no}\n"
printf "${g} SUCCESS ${no}\n"
printf "${y} OK ${no}\n"
printf "${b} BLUE ${no}\n"
printf "${m} MAGENTA ${no}\n"
printf "${c} CYAN ${no}\n"
printf "${w} WHITE ${no}\n"